# Generated by Django 5.2.6 on 2025-09-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name_cyrillic",
                    models.CharField(max_length=255, verbose_name="ФИО (кириллица)"),
                ),
                (
                    "full_name_latin",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ФИО (латиница)"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "bsn",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="BSN"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Номер паспорта",
                    ),
                ),
                (
                    "v_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="V-nummer"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("departed", "Выехал"),
                            ("pending_bsn", "Ожидает BSN"),
                            ("moved", "Перемещён"),
                        ],
                        default="pending_bsn",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "family_group",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Семейная группа",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Жилец",
                "verbose_name_plural": "Жильцы",
                "ordering": ["full_name_cyrillic"],
            },
        ),
    ]
